import React from 'react';
import { Group, Balance, Transaction } from '../types';
import ExpenseList from './ExpenseList';
import BalanceSummary from './BalanceSummary';
import SimplifiedTransactions from './SimplifiedTransactions';

interface PDFReportProps {
  group: Group;
  balances: Balance[];
  transactions: Transaction[];
}

const PDFReport = React.forwardRef<HTMLDivElement, PDFReportProps>(({ group, balances, transactions }, ref) => {
  return (
    <div ref={ref} className="bg-background text-on-surface p-12" style={{ width: '800px' }}>
      <header className="text-center mb-12">
        <h1 className="text-4xl font-bold mb-2">Expense Report</h1>
        <h2 className="text-2xl text-on-surface-secondary">{group.name}</h2>
      </header>
      
      <main className="space-y-10">
        <section className="bg-surface rounded-lg shadow-lg p-6 break-inside-avoid">
          <h3 className="text-2xl font-bold mb-4 text-on-surface border-b border-gray-600 pb-2">Group Members</h3>
          <div className="flex flex-wrap gap-3">
            {group.users.map(user => (
              <span key={user.id} className="bg-background/50 py-2 px-4 rounded-md text-lg">{user.name}</span>
            ))}
          </div>
        </section>

        <section className="break-inside-avoid">
          <BalanceSummary balances={balances} />
        </section>

        <section className="break-inside-avoid">
          <SimplifiedTransactions transactions={transactions} />
        </section>
        
        <section className="break-inside-avoid">
          <ExpenseList expenses={group.expenses} users={group.users} onEdit={() => {}} onDelete={() => {}} isPdf={true} />
        </section>
      </main>

      <footer className="text-center mt-12 text-on-surface-secondary text-sm">
        <p>Report generated by Splitter</p>
        <p>{new Date().toLocaleString()}</p>
      </footer>
    </div>
  );
});

export default PDFReport;